version: 0.1.{build}

init:
  - git config --global core.autocrlf input
nuget:
  project_feed: true

before_build:
  - nuget restore src/owin.sln

platform: Any CPU
configuration: Release

test:
  assemblies:
    - Tests.dll

build:
  publish_nuget: true
  publish_nuget_symbols: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1"
  assembly_file_version: "0.1.{build}"
  assembly_informational_version: "{version}-pre"

notifications:
  - provider: WebHook
    url: https://webhooks.gitter.im/e/0ee040a48ad8006f9f6f
