version: 0.2.{build}

init:
  - git config --global core.autocrlf input
nuget:
  project_feed: true

before_build:
  - nuget restore src/owin.sln

platform: Any CPU
configuration: Release

test:
  assemblies:
    - Tests.dll

build:
  publish_nuget: true
  publish_nuget_symbols: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.2.0"
  assembly_file_version: "0.2.{build}"
  assembly_informational_version: "{version}-pre"

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/207faaaea088565f1b89
    on_build_success: true
    on_build_failure: true
