version: 0.1.{build}-pre

nuget:
  project_feed: true

before_build:
  - nuget restore src/owin.sln

platform: Any CPU
configuration: Release

test:
  assemblies:
    - Tests.dll

build:
  publish_nuget: true
  publish_nuget_symbols: true
