version: 0.1.{build}-pre

install:
  - ps: build/install.ps1

nuget:
  - project_feed: true

before-build:
  - nuget restore src/owin.sln

platform: Any CPU
configuration: Release

test:
  assemblies:
    - Tests.dll
